# version: '3.8'

services:
  drugpreventionsystembe:
    image: ${DOCKER_REGISTRY-}drugpreventionsystembe
    build:
      context: ../DrugPreventionSystemBE
      dockerfile: DrugPreventionSystemBE/Dockerfile
    ports:
      - "8080:80"
      # - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DrugPreventionSystemDB;User Id=SA;Password=MyStrongP@ss2025!;TrustServerCertificate=True;Encrypt=False
    depends_on:
      - sqlserver
    networks:
      - app-network

  # Dịch vụ cho SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyStrongP@ss2025!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver_data:
